object LangCodes {
  val Codes = Map(
    "af" -> "afrikaans",
    "bg" -> "bulgarian",
    "br" -> "breton",
    "ca" -> "catalan",
    "cs" -> "czech",
    "cy" -> "welsh",
    "da" -> "danish",
    "de" -> "german",
    "el" -> "greek",
    "en" -> "english",
    "eo" -> "esperanto",
    "es" -> "spanish",
    "et" -> "estonian",
    "eu" -> "basque",
    "fi" -> "finnish",
    "fr" -> "french",
    "ga" -> "irish",
    "gd" -> "scottish gaelic",
    "gl" -> "galician",
    "he" -> "hebrew",
    "hr" -> "croatian",
    "ia" -> "interlingua",
    "id" -> "bahasa",
    "is" -> "icelandic",
    "it" -> "italian",
    "la" -> "latin",
    "nl" -> "dutch",
    "no" -> "norwegian",
    "pl" -> "polish",
    "pt" -> "portuguese",
    "ro" -> "romanian",
    "ru" -> "russian",
    "se" -> "north sami",
    "sk" -> "slovakian",
    "sl" -> "slovenian",
    "sr" -> "serbian",
    "sv" -> "swedish",
    "tr" -> "turkish",
    "uk" -> "ukrainian")
}
//Codes map {case(a,b) => (a.toLowerCase,b)}